- name: Intall yum packages.
  yum: name={{ item }} state=latest enablerepo="{{ php_enablerepo }}"
  with_items:
    - gd-last
    - graphviz
    - graphviz-gd

- name: Intall yum packages.
  yum: name={{ item }} state=latest enablerepo="{{ php_enablerepo }}"
  with_items: "{{ php_packages }}"

- name: Enable mbstring.
  lineinfile:
    dest: /etc/php.ini
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: '^ *;* *date.timezone *=.*'
      line: 'date.timezone = Asia/Tokyo'
    - regexp: '^ *;* *mbstring.language *=.*'
      line: 'mbstring.language = Japanese'
    - regexp: '^ *;* *mbstring.internal_encoding *=.*'
      line: 'mbstring.internal_encoding = UTF-8'
    - regexp: '^ *;* *mbstring.http_input *=.*'
      line: 'mbstring.http_input = auto'
    - regexp: '^ *;* *mbstring.http_output *=.*'
      line: 'mbstring.http_output = UTF-8'
    - regexp: '^ *;* *session.cookie_httponly *=.*'
      line: 'session.cookie_httponly = true'
    - regexp: '^ *;* *magic_quotes_gpc *=.*'
      line: 'magic_quotes_gpc = Off'

- name: Enable opcache.
  lineinfile:
    dest: /etc/php.d/10-opcache.ini
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: '^ *;\? *opcache.fast_shutdown *= *.*'
      line: 'opcache.fast_shutdown=1'
    - regexp: '^ *;\? *opcache.enable_cli *= *.*'
      line: 'opcache.enable_cli=1'
    - regexp: '^ *;\? *opcache.revalidate_freq *= *.*'
      line: 'opcache.revalidate_freq=5'

- service: name=httpd enabled=yes state=restarted

- name: Install composer.
  shell: php -r "readfile('https://getcomposer.org/installer');" | php
  args:
    chdir: /usr/local/bin
- file:
    src: /usr/local/bin/composer.phar
    dest: /usr/local/bin/composer
    state: link
- file: path=/usr/local/bin/composer.phar state=file mode=755
